### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by tariktesfa** [aimemalaika/portofolio#15]
Hi @aimemalaika,

You have done very well so far 👍 . It would be good if you consider the following to make your portfolio website great.

- In the contact form it would be good if you add the error message for each error type instead of printing all the errors at once so that your contact form will be more interactive.

Congratulation 🥳 🥳 🥳 !!!

**Comment by aimemalaika** [comment]
Thank you for your comments @tariktesfa and @Banstein
