### ISSUE TITLE
Peer-to-peer review

### ISSUE THREAD

**Issue by gtekle** [aimemalaika/portofolio#6]
1. The move-down-arrow needs to be centered. So please add align-items center to the parent of the arrow.

2.  `<h1 class="greeting">Hey there. I’m Aime</h1>` at line number 47 is cropping the text from the right starting at 520px view width.

3. There is a blue vertical line at the left side of the success-button. So please try to remove it by increasing the background size.

**Comment by aimemalaika** [comment]
Thank you @gtekle @rachidelaid and @mrparkersson for your the good catches I will consider fixing the error
